# Generated by Django 4.1.3 on 2022-11-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                 ('Name', models.BigAutoField(auto_created=True, serialize=False, verbose_name='Name')),
                 ('salary', models.BigAutoField(auto_created=True, serialize=False, verbose_name='salary')),
            ],
        ),
    ]
